---
title: "ggplot"
author: "Hendrilalaina"
date: "2025-03-29"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: show
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Packages
```{r}
library(ggplot2)
suppressPackageStartupMessages(library(dplyr))
```
# Data Preparation
```{r}
data("diamonds")
diamonds %>% glimpse()
```
# One Variable

## Discrete
```{r}
diamonds %>%
  ggplot(aes(cut)) +
  geom_bar()
```
## Continious
```{r}
diamonds %>%
  ggplot(aes(x = price)) +
  geom_density()
```

```{r}
diamonds %>%
  ggplot(aes(x = price)) +
  geom_area(stat = "bin")
```
```{r}
diamonds %>%
  sample_n(100) %>%
  ggplot(aes(x = table)) +
  geom_dotplot()
```
```{r}
diamonds %>%
  ggplot(aes(x = price)) +
  geom_histogram()
```
# Two Variables

## Continious X, Continious Y
```{r}
diamonds %>%
  ggplot(aes(x = x, y = y)) +
  geom_point()
```

## Continious X, Discrete Y
```{r}
diamonds %>%
  ggplot(aes(x = price, y = clarity)) +
  geom_jitter(alpha = 0.4)
```

## Discrete X, Continious Y
```{r}
diamonds %>%
  ggplot(aes(x = clarity, y = price)) +
  geom_violin()
```

```{r}
diamonds %>%
  ggplot(aes(x = clarity, y = price)) +
  geom_boxplot()
```

## Discrete X, Discrete Y
```{r}
diamonds %>%
  ggplot(aes(x = clarity, y = cut)) +
  geom_jitter(alpha = 0.4)
```

# Further Dimensions
## Color
```{r}
diamonds %>%
  ggplot(aes(x = x, y = y, col = price)) +
  geom_point() +
  scale_color_continuous(low = "green", high = "red")
```
## Facets
```{r}
diamonds %>%
  ggplot(aes(x = x, y = y, col = price)) +
  geom_point() +
  facet_grid(cut ~ color ) +
  scale_color_continuous(low = "green", high = "red")
```

## Size

```{r}
diamonds %>%
  ggplot(data = ., aes(x = x, y = y, col = price, size = table)) +
  geom_point(alpha = 0.15) +
  facet_grid(cut ~ color) +
  scale_color_continuous(low = "green", high = "red")
```

